In [1]:
import numpy as np
import pandas as pd
import time

In [2]:
arr = np.array([i for  i in range(1,11)])
arr1 = arr + 1
arr2 = arr * 2
arr3 = arr / 3
arr4 = arr - 4

In [3]:
for i in [arr1, arr2, arr3, arr4]:
    print(i)

[ 2  3  4  5  6  7  8  9 10 11]
[ 2  4  6  8 10 12 14 16 18 20]
[0.33333333 0.66666667 1.         1.33333333 1.66666667 2.
 2.33333333 2.66666667 3.         3.33333333]
[-3 -2 -1  0  1  2  3  4  5  6]


In [4]:
start_time_1 = time.time()
arr_copy_1 = np.copy(arr)
for i in range(len(arr)):
    arr_copy_1[i] = arr_copy_1[i] + 1
print(f"Performance Estimation - Elementwise Operation: --- {time.time() - start_time_1} seconds ---")

start_time_2 = time.time()
arr_copy_2 = arr + 1
print(f"Performance Estimation - Vectorize Operation: --- {time.time() - start_time_2} seconds ---")

Performance Estimation - Elementwise Operation: --- 4.7206878662109375e-05 seconds ---
Performance Estimation - Vectorize Operation: --- 2.9087066650390625e-05 seconds ---


In [ ]:
From the above reslt, easy to observe that vectorize operation demonstartes a better performance compared to the element wise operation. In fact, when the data size is large, such outperformence could be more statistically significantly boosted.

In [5]:
df = pd.read_csv("/Users/terranceyan/bootcamp_Terrance_Yan/homework/homework3/data/starter_data.csv")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   category  10 non-null     object
 1   value     10 non-null     int64 
 2   date      10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes


In [7]:
df.head()

category  value        date
0        A     10  2025-08-01
1        B     15  2025-08-02
2        A     12  2025-08-03
3        B     18  2025-08-04
4        C     25  2025-08-05

In [8]:
df_numeric = df.select_dtypes(include='number')
df_numeric.describe()

value
count  10.000000
mean   17.600000
std     7.381659
min    10.000000
25%    12.250000
50%    14.500000
75%    23.250000
max    30.000000

In [9]:
df.groupby("category")

In [10]:
df.describe().to_csv("/Users/terranceyan/bootcamp_Terrance_Yan/homework/homework3/data/processed/summary.csv")

In [11]:
def get_summary_stats(df, name, Export = False, Path = "/Users/terranceyan/bootcamp_Terrance_Yan/homework/homework3/data/processed"):
    if Export:
        df.describe().to_csv(Path + name)
    df.describe()
